# Generated by Django 4.2.7 on 2023-11-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecliente', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=50)),
                ('descripcion', models.PositiveSmallIntegerField()),
                ('abierto', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hola',
        ),
    ]
