# Generated by Django 4.2.7 on 2023-11-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tickets_delete_hola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
