# Generated by Django 4.2.7 on 2023-11-18 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tickets_fecha_alter_tickets_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
