# Generated by Django 4.2.7 on 2023-11-19 05:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tickets_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='fecha',
            field=models.DateField(default=api.models.get_current_date),
        ),
    ]
