# Generated by Django 4.2.7 on 2023-11-19 07:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('client', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=20)),
                ('date', models.DateField(default=api.models.get_current_date)),
            ],
        ),
    ]
