# Generated by Django 4.2.7 on 2023-11-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20),
        ),
    ]
